### PR TITLE
Pin traitsui to >=5.1

### PR DESCRIPTION
**Pull request by christianbrodbeck**
https://github.com/mne-tools/mne-python/issues/4754

### CODE REVIEW

**Comment by larsoner** [comment]
TraitsUI 5.1 was released April 22 2016, and 6 months later https://github.com/enthought/traitsui/pull/311 was merged (on Oct 13, 2016). So doesn't the pin need to be `>5.1`?

**Comment by christianbrodbeck** [comment]
Ah, I checked on my computer and I had 5.1, but I assume then this is a windows-only bug

**Comment by larsoner** [comment]
I hit the issue on Linux or OSX (can't remember which). It's a Python 3 division thing, so should be platform dependent, too. So maybe it's not on 5.1 -- but I'm confused what that PR does, then...

**Comment by christianbrodbeck** [comment]
Aah ok yeah then it probably does nothing useful... I'll close for now until we know a package combination coming from conda-forge that does not work

**Pull request closed without merging**
