### PR TITLE
MAINT: Bump to 1.0

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
So basically, all the `mne-installer-menus`-related stuff
maybe we can just add it to this branch here?

**Comment by hoechenberger** [comment]
> I'm a bit busy right now, can only have a look later today

Ok disregard that, I just freed 15 min and will see how far I'll get

**Comment by larsoner** [comment]
> Ok disregard that, I just freed 15 min and will see how far I'll get

Already pushed

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
