### PR TITLE
New attempt to add an mne-base package

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #37

### CODE REVIEW

**Comment by cbrnr** [comment]
Is this already available in `conda-forge`? I get a `PackagesNotFoundError` when trying to `conda create -y -n mne -c conda-forge mne-base`.

**Comment by hoechenberger** [comment]
This PR just got merged, you gotta be a little more patient! 😜😅 try again in about an hour or so 👍

**Comment by hoechenberger** [comment]
@cbrnr it should work now (just tried it on my Mac)

**Comment by cbrnr** [comment]
For some reason it still doesn't work (conda doesn't find the package). However, I'm sure that it will be available eventually, but do you think that you should then replace `mne` with `mne-base` as a dependency of `mnelab` would be a good idea?

**Comment by hoechenberger** [comment]
> but do you think that you should then replace `mne` with `mne-base` as a dependency of `mnelab` would be a good idea?

Yes we could do that, same for `mne-bids`, I suppose! 
cc @sappelhoff

**Pull request merged**
