### PR TITLE
Depend on pyobjc-framework-cocoa on macOS

### PR DESCRIPTION
**Pull request by hoechenberger**
Otherwise, the Dock icons etc won't be set!

Unfortunately, this makes the `mne` package non-`noarch` :(
(`mne-base` does remain `noarch`, though!)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner Please merge if happy & CI is green

**Comment by larsoner** [comment]
Failure looks real, can't get `sed` on Windows so that will have to be special-cased I think

**Comment by larsoner** [comment]
I guess it must be an issue with combining a `noarch` build with an arch-specific one in the same recipe...?

**Comment by hoechenberger** [comment]
> I guess it must be an issue with combining a `noarch` build with an arch-specific one in the same recipe...?

Seems so, kinda weird. Looks like a limitation (or bug?) in the conda-forge build system…

**Comment by hoechenberger** [comment]
@larsoner this seems to work ... shall we take the risk and merge?

**Comment by hoechenberger** [comment]
Fingers crossed 🤞

**Pull request merged**
