### PR TITLE
Pin pyqt to >=5.10 on macOS, following mne-python installation instructions

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Ok so there's two possible solutions here:

- pin `pyqt >=5.10` for _all_ platforms, or
- drop the `noarch` property

I'm actually in favor of the first one… WDYT?

**Comment by larsoner** [comment]
IIRC the reason we don't just upgrade pyqt5 on all platforms was that broke things on Windows

**Comment by hoechenberger** [comment]
Haha damn. So would you be okay with remove the `noarch` flag from this package then?

**Comment by larsoner** [comment]
> So would you be okay with removing the noarch flag from this package then?

Sure. Or you can try a PR to MNE to change the `environment.yml` to have `pyqt5>=5.10` in the `pip` section and we can see if it succeeds. It's possible in the last year (?) they have updated things and now Windows will work.

**Comment by hoechenberger** [comment]
> Sure. Or you can try a PR to MNE to change the `environment.yml` to have `pyqt5>=5.10` in the `pip` section and we can see if it succeeds. 

I won't be able to manually test on Windows, do you think the CI testing will be sufficient?

**Comment by larsoner** [comment]
[Yes you can](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) :)

But yes we can probably trust the CIs but to be safe I already have Windows VMs I can test with

**Comment by hoechenberger** [comment]
> [Yes you can](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) :)

Ok but I won't ;) Had used such a VM a while back and it was so painfully slow even on a modern computer… 0/5, wouldn't want to do again!

**Comment by hoechenberger** [comment]
Closing for now.

**Pull request closed without merging**
